wireguard: !yamlable/wireguard
  endpoint: vpn.example.com
  interfaces: !yamlable/interfaces
    39a855187c4c4ca694d8c3f215e76cdc: !yamlable/interface
      auto: true
      description: 'vpn for scranton branch'
      gw_iface: eth0
      ipv4_address: 10.0.0.2/24
      listen_port: '52123'
      name: scranton-vpn
      on_down:
      - /usr/sbin/iptables -D FORWARD -i tough-moth -j ACCEPT
      - /usr/sbin/iptables -D FORWARD -o tough-moth -j ACCEPT
      - /usr/sbin/iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      on_up:
      - /usr/sbin/iptables -I FORWARD -i tough-moth -j ACCEPT
      - /usr/sbin/iptables -I FORWARD -o tough-moth -j ACCEPT
      - /usr/sbin/iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
      peers: !yamlable/peers
        9ea085f97fdd4022a16df6f0a70b24db: !yamlable/peer
          description: ''
          dns1: 8.8.8.8
          dns2: ''
          ipv4_address: 10.0.0.3/24
          name: jim halpert
          nat: true
          private_key: KMLxYphCvI4joTyrf3Dp9Yg1vLUj+b8SjLFrUeYnCk0=
          public_key: mvtz+LwXkJur9BkjFmBDOzdE5tacePRfBTFSX4OwmgU=
          uuid: 9ea085f97fdd4022a16df6f0a70b24db
      private_key: 4Ob32NhyhwIXbj7od6L5ASWle3vbOjn9g80at/dxPm0=
      public_key: 7NTAVIucHQJsS9Z8eT3lUV8VUoTSFrB6J272F9ox5RQ=
      uuid: 39a855187c4c4ca694d8c3f215e76cdc
  iptables_bin: /usr/sbin/iptables
  wg_bin: /usr/bin/wg
  wg_quick_bin: /usr/bin/wg-quick
logger: !yamlable/logger
  level: info
  overwrite: false
traffic: !yamlable/traffic
  driver: !yamlable/traffic_storage_driver_json
    timestamp_format: '%d/%m/%Y %H:%M:%S'
  enabled: true
web: !yamlable/web
  login_attempts: 0
  secret_key: G,XhSEIu{>TFu$y?4-kMy+<MN%T*J@/[