# This will only deploy docker images to GHCR
name: latest-deploy
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Set up virtual environment using poetry
        run: |
          wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
          python3 install-poetry.py
          poetry config virtualenvs.create false
          poetry install --no-interaction

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(poetry version -s)"

      - name: Build artifacts
        run: |
          ./build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: "linux/amd64, linux/arm64"
          push: true
